# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f74f529fe2199feae82ed39939b713123c821c0135c42c199506fd7dca7eab154531ce6199d8001e50c12092a40a46733d3c312f938ed3d3ecfa01d622e9b34a

test:
  secret_key_base: 84d94c485704f5f0a86b2d37439e17b59506f2d1ae661a2dfb6d03e1b8bac76c05852f276665dd74020ed2f77d574cbe49d3f1db467de61fda3e945d69fdf78a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
